### ISSUE TITLE
"This can only be used when dead" but I'm dead

### ISSUE THREAD

**Issue by CarlBishop** [benpazzo/AI-Doctor-EMS#2]
Hi and sorry for the issue.

Thank you for this useful resource.

Sometimes when a user call the doctor get the message "This can only be used when dead", but the user IS dead.

Is there something I need to check to fix this?

**Comment by zzazuu** [comment]
> Hi and sorry for the issue.
> 
> Thank you for this useful resource.
> 
> Sometimes when a user call the doctor get the message "This can only be used when dead", but the user IS dead.
> 
> Is there something I need to check to fix this?

Hello there, are you using esx_ambulancejob? this resource is using a callback to that resource to check if the player isDead.

**Comment by CarlBishop** [comment]
Of course I'm using esx_ambulancejob.
I'm also using kashacters it can be the problem
